<?php
/**
 * Created by PhpStorm.
 * User: js
 * Date: 2019-03-07
 * Time: 14:31
 */

define('__WZ_BLOCK__', drupal_get_path('module', 'wz_block'));

/**
 * Implements hook_block_info().
 */
function wz_block_block_info()
{
    $blocks = array(
        'wz_main_slide' =>  array('info' => t('메인 슬라이드')),
        'wz_main_features' => array('info' => t('메인 주요 기사')),
        'wz_main_articles' => array('info' => t('메인 기타 기사')),
        'wz_main_newsletter' => array('info' => t('메인 뉴스레터')),
        'wz_footer' => array('info' => t('웹진 푸터'))
    );

    return $blocks;
}

/**
 * Implements hook_block_configure().
 */
function wz_block_block_configure($delta = '')
{
    $form = array();

    switch ($delta) {
        case 'wz_main_newsletter':
            $form['newsletter_text'] = array(
                '#type' => 'textarea',
                '#title' => '안내문',
                '#default_value' => variable_get('newsletter_text', '')
            );
            $form['newsletter_action'] = array(
                '#type' => 'textfield',
                '#title' => 'Form action URL',
                '#default_value' => variable_get('newsletter_action', '')
            );
            break;
        case 'wz_footer':
            $form['wz_footer'] = array(
                '#type' => 'text_format',
                '#title' => '문구',
                '#default_value' => variable_get('wz_footer', '')
            );
            break;
    }

    return $form;
}

/**
 * Implements hook_block_save().
 */
function wz_block_block_save($delta = '', $edit = array())
{
    switch ($delta) {
        case 'wz_main_newsletter':
            variable_set('newsletter_text', $edit['newsletter_text']);
            variable_set('newsletter_action', $edit['newsletter_action']);
            break;
        case 'wz_footer':
            variable_set('wz_footer', $edit['wz_footer']['value']);
            break;
    }
}

/**
 * Implements hook_block_view().
 */
function wz_block_block_view($delta = '')
{
    $block = array();

    switch ($delta) {
        case 'wz_main_slide':
            $block['content'] = wz_main_slide_block_view();
            break;
        case 'wz_main_features':
            $block['content'] = wz_main_features_block_view();
            break;
        case 'wz_main_articles':
            $block['content'] = wz_main_articles_block_view();
            break;
        case 'wz_main_newsletter':
            $block['content'] = wz_main_newsletter_block_view();
            break;
        case 'wz_footer':
            $block['content'] = array(
                '#type' => 'markup',
                '#markup' => variable_get('wz_footer', '')
            );
            break;
    }

    return $block;
}

function wz_main_slide_block_view()
{
    $main = new Main();                 //메인페이지
    $slide = $main->slide();            //슬라이드
    $html = '<ul class="slide">';
    foreach($slide as $item) {
        $file = file_load($item['fid']);
        $img = image_style_url('main_slide', $file->uri);
        $target = ($item['blank']) ? ' target="_blank"' : '';
        $html .= '<li class="type01">
                    <a href="'.$item['link'].'"'.$target.'>
                        <img src="'.$img.'" alt="'.$item['title'].'"/>
                        <dl>
                            <dt>'.$item['title'].'</dt>
                            <dd>'.nl2br($item['body']).'</dd>
                        </dl>
                    </a>
                </li>';
    }
    $html .='</ul>';

    $block = array(
        'slide' => array(
            '#type' => 'markup',
            '#markup' => $html
        )
    );

    return $block;
}

function wz_main_features_block_view()
{
    $main = new Main();
    $features = $main->features();
    $html = '<div class="inner">';
    foreach($features as $i => $item) {
        $url = drupal_get_path_alias('taxonomy/term/' . $main->category[$i], 'ko');
        $class = ($i === 0) ? 'leftA' : 'rightA';
        $html .= '<div class="'.$class.'">
                    <dl class="th01">
                        <dt>'.$main->featureLabel[$i].'</dt>
                        <dd><a href="/'.$url.'" class="btn_icon02" title="더보기"><i class="xi-plus"></i></a></dd>
                    </dl>
                    <div class="tc01">
                        <a href="/node/'.$item['nid'].'" class="thumb"><img src="'.$item['img'].'" alt=""/></a>
                        <dl class="conA">
                            <dt><a href="/node/'.$item['nid'].'">'.$item['title'].'</a></dt>
                            <dd>'.$item['writer'].'</dd>
                        </dl>

                    </div>
                </div>';
    }
    $html .= '</div>';

    $block = array(
        'features' => array(
            '#type' => 'markup',
            '#markup' => $html
        )
    );

    return $block;
}

function wz_main_articles_block_view()
{
    $main = new Main();
    $articles = $main->articles();
    $html = '<div class="inner">';
    $html .= '<ul class="lc01">';
    $i = 1;
    foreach($articles as $item) {
        $html .= '<li class="l'.$i++.'">
                        <a href="/node/'.$item['nid'].'" class="thumb"><span><img src="'.$item['img'].'" alt="'.$item['title'].'"/></span></a>
                        <dl class="conA">
                            <dt>
                                <i>'.$item['category'].'</i>
                                <a href="/node/'.$item['nid'].'">'.$item['title'].'</a>
                            </dt>
                            <dd>'.$item['writer'].'</dd>
                        </dl>
                    </li>';
    }
    $html .= '</ul>';
    $html .= '<div class="clear"></div>';
    $html .= '</div>';
    $block = array(
        'articles' => array(
            '#type' => 'markup',
            '#markup' => $html
        )
    );

    return $block;
}

function wz_main_newsletter_block_view()
{
    global $base_url;

    $block = array(
        '#prefix' => '<div class="inner">',
        '#suffix' => '</div>',
        'h2' => array(
            '#type' => 'markup',
            '#markup' => '<h2>'.nl2br(variable_get('newsletter_text')).'</h2>'
        ),
        'form' => array(
            '#type' => 'form',
            '#action' => variable_get('newsletter_action', ''),
            'fieldset' => array(
                '#type' => 'fieldset',
                'newsletter' => array(
                    '#type' => 'textfield',
                    '#title' => '이메일',
                    '#id' => 'letter_email',
                    '#name' => 'email',
                    '#attributes' => array('placeholder' => '이메일을 입력하세요')
                ),
                'type' => array(
                    '#type' => 'hidden',
                    '#name' => 'type',
                    '#value' => 'newsletter'
                ),
                'agreed' => array(
                  '#type' => 'hidden',
                  '#name' => 'agreed',
                  '#value' => false,
                  '#attributes' => ['id' => ['agreed']]
                ),
                'submit' => array(
                    '#type' => 'submit',
                    '#value' => '뉴스레터 신청하기',
                    '#attributes' => array('class' => array('btn'))
                )
            ),
            '#attributes' => array(
                'id' => 'newsletter-form',
                'class' => array('cf02')
            ),
            '#attached' => array(
                'library' => array(array('system', 'jquery.form')),
                'js' => array(__WZ_BLOCK__ . '/newsletter.js' => array('type' => 'file', 'scope' => 'footer', 'group' => JS_THEME))
            )
        )
    );
    $block['modal'] = [
      '#markup' => file_get_contents(__WZ_BLOCK__ . '/newsletter-privacy-notice.html'),
      '#attached' => ['css' => [__WZ_BLOCK__ . '/newsletter.css']]
    ];

    return $block;
}
